// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/connectionChange.tsx";
import * as $5 from "./routes/connections.tsx";
import * as $6 from "./routes/delete.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/insertUpdate.tsx";
import * as $9 from "./routes/partials/results/search.tsx";
import * as $10 from "./routes/search.tsx";
import * as $$0 from "./islands/ConnectionDropDown.tsx";
import * as $$1 from "./islands/ConnectionList.tsx";
import * as $$2 from "./islands/DarkMode.tsx";
import * as $$3 from "./islands/PageForm.tsx";
import * as $$4 from "./islands/SearchBox.tsx";
import * as $$5 from "./islands/SearchResults.tsx";
import * as $$6 from "./islands/TabBar.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/connectionChange.tsx": $4,
    "./routes/connections.tsx": $5,
    "./routes/delete.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/insertUpdate.tsx": $8,
    "./routes/partials/results/search.tsx": $9,
    "./routes/search.tsx": $10,
  },
  islands: {
    "./islands/ConnectionDropDown.tsx": $$0,
    "./islands/ConnectionList.tsx": $$1,
    "./islands/DarkMode.tsx": $$2,
    "./islands/PageForm.tsx": $$3,
    "./islands/SearchBox.tsx": $$4,
    "./islands/SearchResults.tsx": $$5,
    "./islands/TabBar.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
